package game;

import java.util.ArrayList;

public class Level {
	private ArrayList<char[][]> blueprints;
	private int currentLevelIndex;
	private ArrayList<Tile> activeTiles;
	private Character player1, player2;
	
	public Level() {
		blueprints = new ArrayList<>();
		activeTiles = new ArrayList<>();
		currentLevelIndex = 0;
		initializeLevels();
	}
	
	//Getters & Setters
	public ArrayList<Tile> getActiveTiles(){
		return activeTiles;
	}
	public Character getPlayer1() { return player1;}
	public Character getPlayer2() { return player2;}
	
	//Methods
	private void initializeLevels() {
		//each level is 15 rows by 20 columns
		char[][] level1 = {
			//this is a practice level generated by gemini	
				{'W','W','W','W','W','W','W','W','W','W','W','W','W','W','W','W','W','W','W','W'}, // Row 0
		        {'W','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','D','E','W'}, // Row 1
		        {'W','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','W'}, // Row 2
		        {'W','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','W'}, // Row 3
		        {'W','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','W'}, // Row 4
		        {'W','W','W','W','W','.','.','W','W','W','W','W','W','.','.','W','W','W','W','W'}, // Row 5
		        {'W','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','W'}, // Row 6
		        {'W','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','W'}, // Row 7
		        {'W','.','.','R','.','.','.','.','.','.','.','.','.','.','.','B','.','.','.','W'}, // Row 8
		        {'W','.','.','W','W','W','W','W','.','.','.','.','W','W','W','W','W','.','.','W'}, // Row 9
		        {'W','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','W'}, // Row 10
		        {'W','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','W'}, // Row 11
		        {'W','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','W'}, // Row 12
		        {'W','F','M','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','W'}, // Row 13
		        {'W','W','W','W','W','W','W','W','W','W','W','W','W','W','W','W','W','W','W','W'}  // Row 14
		};
		blueprints.add(level1);
	}
	
	public void printCurrentLevelToConsole() {
		char[][] currentMap = blueprints.get(currentLevelIndex);
		System.out.println("Loading level " + (currentLevelIndex +1) + ":\n");
		
		for(int row = 0; row<currentMap.length; row++) {
			for(int col = 0; col<currentMap[row].length; col++) {
				System.out.print(currentMap[row][col] + " ");
			}
			System.out.println();
		}
		
		
	}
	
	/**
	 * Loads the level at the current index to be drawn on the screen
	 */
	public void loadCurrentLevel() {
		activeTiles.clear();
		char[][] map = blueprints.get(currentLevelIndex);
		
		for(int row = 0; row<map.length; row++) {
			for(int col = 0; col<map[row].length; col++) {
				char symbol = map[row][col];
				//x & y values for each tile
				int xPixel = col * 40;
				int yPixel = row * 40;
				
				if(symbol=='W') {
					activeTiles.add(new Wall(xPixel, yPixel, 40, 40));
				}
				else if(symbol=='R') {
					activeTiles.add(new Gem(xPixel, yPixel, 40, 40, "Red"));
				}
				else if(symbol=='B') {
					activeTiles.add(new Gem(xPixel, yPixel, 40, 40, "Blue"));
				}
				else if(symbol=='D') {
					activeTiles.add(new Door(xPixel, yPixel, 40, 40, "Red"));
				}
				else if(symbol=='E') {
					activeTiles.add(new Door(xPixel, yPixel, 40, 40, "Blue"));
				}
				else if(symbol=='X') {
					activeTiles.add(new Lava(xPixel, yPixel, 40, 40, "Red"));
				}
				else if(symbol=='Y') {
					activeTiles.add(new Lava(xPixel, yPixel, 40, 40, "Blue"));
				}
				else if (symbol == 'O') {
	                activeTiles.add(new Button(xPixel, yPixel, 40, 40));
				}
	            else if (symbol == 'L') {
	                activeTiles.add(new Lever(xPixel, yPixel, 40, 40, false));
	            }
	            else if(symbol == 'F') {
	            	player1 = new Character(xPixel, yPixel, 30, 30, "Red", true);
	            }
	            else if(symbol == 'M') {
	            	player2 = new Character(xPixel, yPixel, 30, 30, "Blue", false);
	            }
			}
		}
		System.out.println("Level loaded! Active tiles: " + activeTiles.size() );
		
	}
}
