package game;

import java.util.ArrayList;

public class Level {
	private ArrayList<char[][]> blueprints;
	private int currentLevelIndex;
	private ArrayList<Tile> activeTiles;
	
	public Level() {
		blueprints = new ArrayList<>();
		activeTiles = new ArrayList<>();
		currentLevelIndex = 0;
		initializeLevels();
	}
	
	private void initializeLevels() {
		//each level is 15 rows by 20 columns
		char[][] level1 = {
			//this is a practice level generated by gemini	
				{'W','W','W','W','W','W','W','W','W','W','W','W','W','W','W','W','W','W','W','W'}, // Row 0
		        {'W','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','D','E','W'}, // Row 1
		        {'W','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','W'}, // Row 2
		        {'W','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','W'}, // Row 3
		        {'W','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','W'}, // Row 4
		        {'W','W','W','W','W','.','.','W','W','W','W','W','W','.','.','W','W','W','W','W'}, // Row 5
		        {'W','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','W'}, // Row 6
		        {'W','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','W'}, // Row 7
		        {'W','.','.','R','.','.','.','.','.','.','.','.','.','.','.','B','.','.','.','W'}, // Row 8
		        {'W','.','.','W','W','W','W','W','.','.','.','.','W','W','W','W','W','.','.','W'}, // Row 9
		        {'W','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','W'}, // Row 10
		        {'W','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','W'}, // Row 11
		        {'W','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','W'}, // Row 12
		        {'W','F','M','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','.','W'}, // Row 13
		        {'W','W','W','W','W','W','W','W','W','W','W','W','W','W','W','W','W','W','W','W'}  // Row 14
		};
		blueprints.add(level1);
	}
	
	public void printCurrentLevelToConsole() {
		char[][] currentMap = blueprints.get(currentLevelIndex);
		System.out.println("Loading level " + (currentLevelIndex +1) + ":\n");
		
		for(int row = 0; row<currentMap.length; row++) {
			for(int col = 0; col<currentMap[row].length; col++) {
				System.out.print(currentMap[row][col] + " ");
			}
			System.out.println();
		}
		
		
	}
	public void loadCurrentLevel() {
		activeTiles.clear();
		char[][] map = blueprints.get(currentLevelIndex);
		
		for(int row = 0; row<map.length; row++) {
			for(int col = 0; col<map[row].length; col++) {
				
				char symbol = map[row][col];
				
			}
		}
		
		
	}
}
